### PR TITLE
Add Events API from Google Sheets

### LINKED ISSUE #1: Add live schedule storage
Add an endpoint with live schedule that pulls from Google Sheets or a yaml or something.

It should be cached agressively every 15 minutes to avoid being rate limited.

### PR DESCRIPTION
**Pull request by peasant98**
## What this PR does / Why we need it
Added in the first version of the new endpoint to the Hack CU Api. Currently users can make a get request to **/sheets/events/**, which will return JSON of all of the events.

The JSON is structured so that 'day1' and 'day2' each have an array of events where one event is structured like:

{"Location": "Idea Forge", "Start": "7:00 AM", "Description": "Check-In", "End": "8:00 AM"}

("Idea Forge" is the default location currently)

All of the events are displayed upon making a GET request to this endpoint, and I anticipate on having more code that takes into account when the request was made so it shows the next several events from then. 

## Which issue(s) this PR fixes (optional)

Fixes #1 
## Special notes for your reviewer (optional)

I use pandas to read the csv, and I split the table by day 1 and day 2, and can convert the dataframe to a dictionary that is returned as JSON. More changes on the way!

Second change:

I use csv and requests without pandas to do similar work. Fixed formatting errors as well.

## Some questions
- [X] I have read the contributing guidelines
- [X] I abide by this repository Code of Conduct
- [X] I understand that my PR won't be merged until Travis gives a "green light"

## Additional Notes (optional)
Let me know if there are any bugs or new features to fix, I'll be on it!

### CODE REVIEW

**Comment by casassg** [comment]
Please, stop closing and opening PRs. Keep one open and push commits to it. That should trigger the build as well.

**Comment by casassg** [comment]
Errors on formatting:

```
./slack/views.py:27:23: W291 trailing whitespace
./sheets/spreadsheet.py:2:1: F401 'json' imported but unused
./sheets/spreadsheet.py:3:1: F401 'time' imported but unused
./sheets/spreadsheet.py:8:1: E302 expected 2 blank lines, found 1
./sheets/spreadsheet.py:9:26: W291 trailing whitespace
./sheets/spreadsheet.py:15:20: E226 missing whitespace around arithmetic operator
./sheets/spreadsheet.py:27:1: E305 expected 2 blank lines after class or function definition, found 1
./sheets/tests.py:1:1: F401 'django.test.TestCase' imported but unused
./sheets/models.py:1:1: F401 'django.db.models' imported but unused
./sheets/admin.py:1:1: F401 'django.contrib.admin' imported but unused
./sheets/views.py:1:1: F401 'django.shortcuts.render' imported but unused
./sheets/views.py:2:1: F401 'json' imported but unused
./sheets/views.py:3:1: F401 'django.conf.settings' imported but unused
./sheets/views.py:5:1: F401 'rest_framework.response.Response' imported but unused
./sheets/views.py:7:1: W293 blank line contains whitespace
./sheets/views.py:11:1: E302 expected 2 blank lines, found 1
./sheets/views.py:12:38: W291 trailing whitespace
./sheets/views.py:19:1: E303 too many blank lines (3)
./sheets/views.py:19:1: E265 block comment should start with '# '
./sheets/views.py:23:82: W291 trailing whitespace
./sendgrid/views.py:32:23: E231 missing whitespace after ':'
./sendgrid/views.py:32:40: E231 missing whitespace after ':'
./sendgrid/views.py:35:26: E231 missing whitespace after ':'
./sendgrid/views.py:35:42: E231 missing whitespace after ':'
```

**Comment by casassg** [comment]
Also, can this be done without pandas?

**Comment by peasant98** [comment]
Made a change:

used csv + request instead of pandas to return the json, and I return a JSON of
{'day1' : [], 'day2': []}, where each day has its corresponding events.

also fixed formatting errors as well. Seems like the build fails for python 2 (related to the astroid package).

**Pull request merged**
